version: "3"
services:
  # the redis session database
  redis:
    image: redis
    container_name: sessiondb
    expose:
      - 6379
  # the arangodb database
  arangodb:
    image: arangodb/arangodb
    container_name: userdb
    environment:
      - ARANGO_ROOT_PASSWORD=justfortest
    expose:
      - 8529
    volumes:
      - ./database/arangodb:/var/lib/arangodb3
      - ./database/arangoapps:/var/lib/arangodb3-apps
  # jolocom server
  jolocom:
    container_name: jolocom
    build: ./sdk-rpc-interface/packages/server/
    volumes:
      - ./database/jolocom/data:/data
    ports:
      - '4040:4040'
    #expose:
    #  - 4040
    environment:
      DATABASE_DIR: '/data'
      AGENT_PASSWORD: 'hunter2'
  # condidi backend
  condidibackend:
    build: ./src/
    ports:
      - 8080:8080
    environment:
      - REDIS_HOST=redis
      - ARANGO_URL=arangodb:8529
      - DEVELOPMENT=False
      - PORT=8080
    depends_on:
      - redis
      - arangodb
      - jolocom