# docker compose file to run the databases for local development and tests
# databases will be accessible from the outside! Use just for testing!
# the redis session database
redis:
  image: redis
  container_name: sessiondb
  ports:
    - "6379:6379"
# the arangodb database
arangodb:
  image: arangodb/arangodb
  container_name: userdb
  environment:
    - ARANGO_ROOT_PASSWORD=justfortest
  ports:
    - "8529:8529"
  volumes:
    - ./database/arangodb:/var/lib/arangodb3
    - ./database/arangoapps:/var/lib/arangodb3-apps

